name: Upload asset to v1.0.0 release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload asset to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.0
          files: releases/v1.0.0/MarsXZMedia_Setup.exe
